---
version: "3"

vars:
  ANSIBLE_DIR: "{{.ROOT_DIR}}/ansible"
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"

env:
  KUBECONFIG: "{{.ROOT_DIR}}/kubeconfig"

includes:
  workstation: .taskfiles/WorkstationTasks.yaml
  ansible: .taskfiles/AnsibleTasks.yaml


tasks:
  default:
    silent: true
    cmds: ["task -l"]